apiVersion: v1
kind: Service
metadata:
  name: react-todo-app-service
  labels:
    app: react-todo-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: react-todo-app
